### ISSUE TITLE
keycloak-mysql:1.1.0.Final builds from 1.2.0.Beta1

### ISSUE THREAD

**Issue by alancnet** [jboss-dockerfiles/keycloak#12]
In /server-mysql/Dockerfile, you see FROM jboss/keycloak, so the automated build pulls the latest version (1.2.0.Beta1).

This from line needs to be changed to FROM jboss/keycloak:1.1.0.Final

![image](https://cloud.githubusercontent.com/assets/2042102/7150713/00ab0162-e2dc-11e4-8496-de6dc430a282.png)

**Comment by stianst** [comment]
This is fixed from 1.2.0.Beta1 onwards

**Comment by alancnet** [comment]
I see that, however the 1.1.0.Final distribution is broken

**Comment by stianst** [comment]
Ok - should be fixed for 1.1.0.Final as well now
