### ISSUE TITLE
Support for schema?

### ISSUE THREAD

**Issue by kesavkolla** [jboss-dockerfiles/keycloak#14]
is there any way pass schema as environment variable.  I've a multi-tenant application where each tenant is in different schema. Is it possible to configure keycloak for this?

**Comment by stianst** [comment]
We plan to support specifying schema in next version of Keycloak. This will specify the schema used for the all realms though. We're not planning to support different DB config on a per-realm basis.

**Comment by stianst** [comment]
Please, use JIRA for issues
