### ISSUE TITLE
When 1.3.1.Final image will be released? \o/

### ISSUE THREAD

**Issue by ayr-ton** [jboss-dockerfiles/keycloak#23]

**Comment by goldmann** [comment]
Soon :)

**Comment by goldmann** [comment]
All builds are pending now.

**Comment by ayr-ton** [comment]
Thank you! \o/

**Comment by goldmann** [comment]
Images released.

**Comment by ayr-ton** [comment]
@goldmann Theres a bug in 1.3.1.Final for postgres environemnts:
https://github.com/jboss-dockerfiles/keycloak/pull/24

**Comment by ayr-ton** [comment]
I think it will be necessary to rebuild the tag 1.3.1.Final with the last corrections for make it works fine.

Thanks!

**Comment by goldmann** [comment]
It's in-progress right now.

**Comment by ayr-ton** [comment]
Thank you for all the care, @goldmann x)

**Comment by goldmann** [comment]
You welcome. Stuff should be now online, or will be there shortly.

**Comment by ayr-ton** [comment]
Ahhh. There's a tag missing here:
https://registry.hub.docker.com/u/jboss/keycloak-ha-postgres/

**Comment by goldmann** [comment]
I'll fix it tomorrow. Ping me if I forget ;)
