### ISSUE TITLE
Saxon not importing database settings at 1.3.1.Final

### ISSUE THREAD

**Issue by ayr-ton** [jboss-dockerfiles/keycloak#25]
At version 1.3.1, at the second step of the Dockerfile:

RUN java -jar /usr/share/java/saxon.jar -s:/opt/jboss/keycloak/standalone/configuration/standalone.xml -xsl:/opt/jboss/keycloak/changeDatabase.xsl -o:/opt/jboss/keycloak/standalone/configuration/standalone.xml; java -jar /usr/share/java/saxon.jar -s:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml -xsl:/opt/jboss/keycloak/changeDatabase.xsl -o:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml; rm /opt/jboss/keycloak/changeDatabase.xsl

saxon is not writing the changeDatabase.xsl data into /opt/jboss/keycloak/standalone/configuration/standalone.xml or standalone-ha.xml.

No error output is given even if I manually run this step inside the container. It act like everything is fine but when I open the standalone.xml, this is the default settings.

I could not figure out yet a solution for this in meaning to provide a PR. Does someone know's how to fix this?

**Comment by vst** [comment]
I just bumped into this, too. Please check this out: #26. Very simple to make it work back again.

**Comment by ayr-ton** [comment]
@vst Thank you very much! 

![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.trcpodcast.com%2Fwp-content%2Fuploads%2F2013%2F03%2Fdawson-crying.jpg)
