### ISSUE TITLE
Export action parameters are ignored

### ISSUE THREAD

**Issue by ralgara** [jboss-dockerfiles/keycloak#28]
Using `./standalone.sh -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp` as indicated in [docs](http://docs.jboss.org/keycloak/docs/1.0-final/userguide/html/export-import.html) results in a normal startup, but the export action arguments seem to be completely ignored.

**Comment by stianst** [comment]
Please use https://issues.jboss.org/browse/KEYCLOAK to report issues
