### ISSUE TITLE
Usage section in READMEs could include -p 8080:8080 in command and url for console

### ISSUE THREAD

**Issue by grange74** [jboss-dockerfiles/keycloak#33]
Obviously there is some assumed Docker knowledge with the instructions but i thought it could be slightly improved so that it is easier for Docker and/or Keycloak newbies. 
The port mapping just makes it easier for people so they don't have to go looking up the containers IP or work out how to access it. Binding to the host generally makes it easier.
As for the url, you can just go to http://ip:8080 and you'll get a screen with a link to the admin console but it would be nice to have the exact url upfront. I couldn't see it in Keycloak's start up output either.

So for example for the main Keycloak docker image
https://github.com/jboss-dockerfiles/keycloak/tree/master/server

## Before

To boot in standalone mode

    docker run jboss/keycloak

Once it boots, you can login to the admin console using admin/admin for the first login.

## After

To boot in standalone mode

    docker run -p 8080:8080 jboss/keycloak

Once it boots, you can login to the admin console at ```http://{hostip}:8080/auth/admin/``` using admin/admin for the first login.

I'm happy to make the changes if you are ok with the suggestion.

**Comment by stianst** [comment]
This comes up again and again, but we're not going to add this.

**Comment by grange74** [comment]
Prior to creating the issue i did look to see if an issue had already been raised, at the time i did not see the rejected PR: https://github.com/jboss-dockerfiles/keycloak/pull/27

After reading the response to that PR, i'm quite saddened by the hard-line attitude. 
While generally there is merit in not over documenting something that is already documented elsewhere, the fact that it comes up again and again is evidence enough that this is not the case here. 

Regardless, i believe the bigger picture is being missed here. Someone has tried out your open source project and followed your instructions. They have probably spent at least an hour trying to work out why they can't get it to work and to their credit they didn't give up (as many would). 
Then they have thought about trying to help others so that they don't go through the same painful experience and in true open source spirit they spent their own time forking the repo, making the change and submitting a pull request. All to have someone reject it on a technicality.

This project would be much better off if it tried to follow the rules on this post on being a [good open source community member](http://spf13.com/post/how-to-be-a-good-open-source-community-member/).

**Comment by grange74** [comment]
Btw @stianst you might want to remove the port mapping and URL from the Wildfly docker image readme as i'm sure you don't want people thinking that you are inconsistent as per https://github.com/jboss-dockerfiles/keycloak/pull/10. 

It is probably best not to deprive people of working out that they need to do a docker inspect after following the instructions, trawling through the JSON to find the IP and port and then work out how to access the 172.X.X.X range from their browser. 

Also if you are worried about preventing people from not "running multiple WF/KC instances" then it would be much easier to just put ```-p 8080``` and let docker allocate a random port on the host. A simple ```docker ps``` will give the port clearly. Though the average user who is going to be copy-paste your instructions isn't likely to be running a second instance when they can't get the first to work. :-)

Run it:

    docker run -it -p 9990:9990 jboss/wildfly-admin

The administration console should be available at **http://localhost:9990**.

https://github.com/jboss-dockerfiles/wildfly/blob/master/README.md

**Comment by goldmann** [comment]
I'm the maintainer of the WildFly image. Basically I agree with @stianst in this case. We have the port enabled in the extending the image section (at the time of writing it I wanted to highlight the port number of the console) but we don't have in the usage instructions at the top. I'll remove the port entirely.

**Comment by stianst** [comment]
End of the day some will want to expose it on a local port, others will want to use the IP allocated to the IP, some will want to run it as a demon, others not. There's so many basic Docker instructions we can include in the  README. However, there are plenty of sources that explain those things, so we're not going to duplicate it in our README files. Have a look at https://docs.docker.com/articles/basics/ that will not only mention -p, but also explain it. We have plenty of work to do other than duplicating basic instructions around Docker.

We may however include something like this in a getting started with Keycloak on Docker guide, if we ever get time to write it.

**Comment by goldmann** [comment]
WildFly updated: https://github.com/jboss-dockerfiles/wildfly/commit/75e35f5194d665fbb48d32943a0ad11b2c89a3da

**Comment by grange74** [comment]
All i'm trying to do is make it easier for people to start using your product. I like Keycloak and i've spent a considerable time with it over the last few months. 
You need to realise that as core maintainers you are often not in the best position to see what a newcomers will see as you use it every day.

If it was only me thinking this than why have there been 2 separate pulls requests on this repo alone prior to the issue i raised. Don't you think that there is a problem?

As for docker basics, why have the ```docker run jboss/keycloak``` command in the first place on the instructions?
Just have a link to docker and tell them the docker image name. They should know the rest, right?

Btw I'm been using docker for over a year now and still i still go caught by it. Maybe it's just me though i doubt it.

**Comment by stianst** [comment]
If you really want to help feel free to write a getting started with Keycloak on Docker guide. We'll be happy to post it on our blog and we'll most likely include it in our Documentation as well.

**Comment by grange74** [comment]
Thank you. 
It is much better to suggest an alternative than a straight out no. If people are willing to contribute their own time to help the project, then you really should take advantage of it rather than fight it and turn people away. Docker is a great example of how successful something can be if you get it right and turn a small team of paid developers into large army of mostly external contributors.
