### ISSUE TITLE
Keycloak-mysql-server setup

### ISSUE THREAD

**Issue by josemolmomillan** [jboss-dockerfiles/keycloak#8]
Hello

    I have setup a Keycloak-mysql server with a external mysql DB.

    I would like to initialize the Keycloak DB with the execution of  "curl" command for Keycloak Admin Rest API. do you have some example about this?

   I am trying something similar to this:
     curl -vXi POST http://admin:admin@localhost:8081/auth/admin/realms/ -d @keycloak.json --header "Content-Type: application/json"  but I have different issues related to auth token.

Thanks in advance
Regards

**Comment by jpkrohling** [comment]
Please, use the keycloak-user mailing list for such questions: https://lists.jboss.org/mailman/listinfo/keycloak-user .
